networks:
  valkey-net:
    driver: bridge
services:
  valkey-1: &valkey-base
    image: valkey/valkey:9.0.3
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    networks:
      - valkey-net
    container_name: valkey-1
    volumes:
      - ./conf/node-1:/usr/local/etc/valkey
      - ./data/node-1:/data
    ports:
      - "6380:6379"
      - "16380:16380"
  valkey-2:
    <<: *valkey-base
    container_name: valkey-2 
    volumes:
      - ./conf/node-2:/usr/local/etc/valkey
      - ./data/node-2:/data
    ports:
      - "6381:6379"
      - "16381:16380"
  valkey-3:
    <<: *valkey-base
    container_name: valkey-3 
    volumes:
      - ./conf/node-3:/usr/local/etc/valkey
      - ./data/node-3:/data
    ports:
      - "6382:6379"
      - "16382:16380"
  valkey-4:
    <<: *valkey-base
    container_name: valkey-4
    volumes:
      - ./conf/node-4:/usr/local/etc/valkey
      - ./data/node-4:/data
    ports:
      - "6383:6379"
      - "16383:16380"
  valkey-5:
    <<: *valkey-base
    container_name: valkey-5
    volumes:
      - ./conf/node-5:/usr/local/etc/valkey
      - ./data/node-5:/data
    ports:
      - "6384:6379"
      - "16384:16380"
  valkey-6:
    <<: *valkey-base
    container_name: valkey-6
    volumes:
      - ./conf/node-6:/usr/local/etc/valkey
      - ./data/node-6:/data
    ports:
      - "6385:6379"
      - "16385:16380"
